Repository AxeWP/wp-graphql-gravity-forms, pull requests merged in 2022-10, with the labels that each got.

#316 release: 0.11.6
  CHANGELOG.md
  composer.json
  composer.lock
  src/Extensions/GFQuiz/Type/WPObject/FormField/FieldProperty/PropertyMapper.php
  src/Type/WPObject/FormField/FieldProperty/ChoiceMapper.php
  vendor/composer/installed.php
Labels: type: bug 🐛, safe to test ✔

#319 fix: Check for falsey `personalData` when resolving the form model.
  CHANGELOG.md
  src/Model/Form.php
Labels: type: bug 🐛, safe to test ✔

#321 Release: v0.11.7
  CHANGELOG.md
  README.md
  composer.lock
  readme.txt
  src/Data/Loader/FormsLoader.php
  src/Extensions/GFQuiz/Type/WPObject/Form/FormQuiz.php
  src/Model/Form.php
  tests/wpunit/FormQueriesTest.php
  vendor/composer/installed.php
  wp-graphql-gravity-forms.php
Labels: safe to test ✔

#329 docs: use full syntax for listValues example
  docs/submitting-forms.md
Labels: scope: documentation 📚, type: chore 🧹

#330 Use WP_CLI_ALLOW_ROOT env variable
  bin/_lib.sh
Labels: type: enhancement ⚡, scope: build scripts 🔧, type: chore 🧹, safe to test ✔

#331 release: v0.11.8
  CHANGELOG.md
  README.md
  composer.lock
  readme.txt
  src/Type/WPObject/FormField/FieldProperty/FieldProperties.php
  vendor/composer/installed.php
  wp-graphql-gravity-forms.php
Labels: safe to test ✔
